### PR TITLE
Fixing Material Foundation's TypeScript Color Utilities Library (again)

### LINKED ISSUE #79: Typescript utils won't install with the new version ( 0.2.1 )
The new version that was just published throws a bunch of errors when trying to install with `npm i` 
```
npm ERR! command failed
npm ERR! command sh -c npm run build
npm ERR! > @material/material-color-utilities@0.2.1 build
npm ERR! > npm run remove-build && tsc
npm ERR! 
npm ERR! 
npm ERR! > @material/material-color-utilities@0.2.1 remove-build
npm ERR! > rm -rf dist
npm ERR! 
npm ERR! blend/blend_test.ts(24,1): error TS2304: Cannot find name 'beforeEach'.
npm ERR! blend/blend_test.ts(25,3): error TS2708: Cannot use namespace 'jasmine' as a value.
npm ERR! blend/blend_test.ts(33,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(34,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(36,5): error TS2304: Cannot find name 'expect'.
npm ERR! blend/blend_test.ts(39,3): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
npm ERR! blend/blend_test.ts(41,5): error TS2304: Cannot find name 'expect'.
...
```

### PR DESCRIPTION
**Pull request by WillsterJohnson**
Fixes #79 

TODO list;

- [x] reduce bulk and excess
- [x] don't run build scripts when users install a package
- [x] ensure build works
- [x] ensure tests pass
- [ ] teach the world-class engineers at Google (a globally known houshold name) how `package.json` works

### CODE REVIEW

**Comment by rodydavis** [comment]
Thank you for the change, there is some context for why we had this in the package.json but due to changes in how we publish it was no longer needed.

This comment is incredibly rude and against our [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md), and keep in mind all comments made on open source repos are available forever.

In the future please comment with respect and constructive feedback. These repos require work to open source and get working properly.

**Comment by WillsterJohnson** [comment]
My apologies for my rudeness.
I hope you can understand the frustration I feel though, as the Material Design System is something I find to be as close to perfection as possible, and yet using it is blocked by simple issues like this. My frustration is not meant to be directed at any of your team, just generally at Google due to their long-standing pattern of "make something amazing then under-support it's progression".
I am very grateful for the work done by the material foundation, especially for open sourcing this library and continuing to support fixes and improvments.

**Comment by rodydavis** [comment]
0.2.2 is live!

**Comment by rodydavis** [comment]
Latest code is pushed to main, working on publishing to npm

**Pull request closed without merging**
