### PR TITLE
fix sourceColorFromImage bug if image load complete and partly image

### PR DESCRIPTION
**Pull request by mindon**
1. fix load complete image bug
2. support using part of image with data-area 

This repo is not *currently* accepting external contributions, but feature
requests and bug reports are very welcome!

### CODE REVIEW

**Comment by guidezpl** [comment]
@rodydavis could you please take a look at integrating this change?

**Comment by rodydavis** [comment]
Integrated on internal change that we will push out

**Comment by guidezpl** [comment]
thanks!

**Comment by rodydavis** [comment]
landed on the latest!

**Pull request closed without merging**
